sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 666666
#  alioss:
#    endpoint: oss-cn-aliyuncs.com
#    access-key-id: YOUR_ACCESS_KEY_ID
#    access-key-secret: YOUR_ACCESS_KEY_SECRET
#    buckey-name: sky-itcast
  redis:
    host: 172.27.102.175
    port: 6379
    password: 666666
    database: 2
  wechat:
    appid: wxe17e68915ea96f29
    secret: 18fd8659be177446d15c9ab4e01ad1e9

